@baseURI = https://0iyhvjnmbd.execute-api.us-east-1.amazonaws.com/dev


#########
# Get settings
GET {{baseURI}}/productsSchedules/settings
Authorization: Bearer {{accessToken}}

#########
# Get 1 day by date
GET {{baseURI}}/productsSchedules/date?onlyDate=2020-05-26
Authorization: Bearer {{accessToken}}

#########
# Get 3 days by date
GET {{baseURI}}/productsSchedules/date?firstDate=2020-05-26&lastDate=2020-05-28
Authorization: Bearer {{accessToken}}

#########
# Get 3 days by date and omit onsite products
GET {{baseURI}}/productsSchedules/date?firstDate=2020-05-26&lastDate=2020-05-29&omitType=onsite
Authorization: Bearer {{accessToken}}

#########
# Update schedule data
GET {{baseURI}}/productsSchedules/update
Authorization: Bearer {{accessToken}}

#########
# Replace schedule data
GET {{baseURI}}/productsSchedules/replace
Authorization: Bearer {{accessToken}}
