@baseURI = https://0iyhvjnmbd.execute-api.us-east-1.amazonaws.com/dev


#########
# Get settings
GET {{baseURI}}/productsSchedules/settings
Authorization: Bearer {{accessToken}}

#########
# Get 1 day of products by date that are relevant after 1 pm
GET {{baseURI}}/productsSchedules/settings

#########
# Triton testing
GET https://triton.mos.org/products/productsTodayMOSatHome14Days.json

#########
# Triton testing
GET https://triton.mos.org/products/productsTodayDailyScheduleFeed.json