custom:
  config:
    stage: dev
#-------------
provider:
  runtime: nodejs12.x
  profile: mos-api-programmatic-admin
authJWTPayloadMessage: ${ssm:auth-jwt-payload-message}
authJWTPayloadSecret: ${ssm:auth-jwt-secret}
authMOSAPISLSAdminAccessKeyID: ${ssm:auth-mos-api-sls-admin-access-key-id}
authMOSAPISLSAdminSecretAccessKey: ${ssm:auth-mos-api-sls-admin-secret-access-key}
cronScheduleEmailQueueProcessing: ${ssm:cron-schedule-email-queue-processing}
cronScheduleGSEJobSync: ${ssm:cron-schedule-gse-job-sync}
cronScheduleGSEScheduleSync: ${ssm:cron-schedule-gse-schedule-sync}
cronScheduleGSESignupSync: ${ssm:cron-schedule-gse-signup-sync}
cronScheduleGSESignupReminders: ${ssm:cron-schedule-gse-signup-reminders}
cronScheduleGSECreditReminders: ${ssm:cron-schedule-gse-credit-reminders}
cronSchedulePeopleProcessing: ${ssm:cron-schedule-people-processing}
graphClientID: ${ssm:graph-client-id}
graphClientSecret: ${ssm:graph-client-secret}
graphTenantID: ${ssm:graph-tenant-id}
mongoDbHostUnique: ${ssm:mongodb-host-unique}
mongoDbPass: ${ssm:mongodb-pass}
mongoDbUser: ${ssm:mongodb-user}
spClientID: ${ssm:sp-client-id}
spClientSecret: ${ssm:sp-client-secret}
twitterConsumerKey: ${ssm:twitter-consumer-key}
twitterConsumerSecret: ${ssm:twitter-consumer-secret}
twitterAccessTokenKey: ${ssm:twitter-access-token-key}
twitterAccessTokenSecret: ${ssm:twitter-access-token-secret}
upApiKey: ${ssm:up-api-key}
upEmployeeChangesPass: ${ssm:up-emp-changes-pw}
upEmployeeChangesUser: ${ssm:up-emp-changes-user}
endpoints:
  dev:
    access:
      awsCredentials:                   access/aws-credentials
    email:
      send:                             email/send
    files:
      settings:                         files/settings
      drive:                            files/drive
      driveChildren:                    files/drive/children
      driveChild:                       files/drive/child
      folder:                           files/folder
      file:                             files/file
    health:
      check:                            health/check
    hubLists:
      settings:                         hubLists/settings
      list:                             hubLists/list
      items:                            hubLists/items
    hubMessages:
      settings:                         hubMessages/settings
      messages:                         hubMessages/messages
      add:                              hubMessages/add
      update:                           hubMessages/update
      nextID:                           hubMessages/nextid
    hubSites:
      settings:                         hubSites/settings
      site:                             hubSites/site
      drives:                           hubSites/drives
      lists:                            hubSites/lists
    people:
      process:                          people/process
      all:                              people/all
      person:                           people/person
      org:                              people/org
      department:                       people/department
      division:                         people/division
      departments:                      people/departments
      managers:                         people/managers
      managersDownlinesFlat:            people/managers/downlines/flat
      managersDownlinesHierarchical:    people/managers/downlines/hierarchical
      managerDownlineDirect:            people/manager/downline/direct
      managerDownlineFlat:              people/manager/downline/flat
      managerDownlineHierarchical:      people/manager/downline/hierarchical
      personUpline:                     people/person/upline/flat
